// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: camera_service.proto
#ifndef GRPC_camera_5fservice_2eproto__INCLUDED
#define GRPC_camera_5fservice_2eproto__INCLUDED

#include "camera_service.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

// Define the service
//
class CameraService final {
 public:
  static constexpr char const* service_full_name() {
    return "CameraService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Define the RPC method for sending camera data
    //
    virtual ::grpc::Status SendCameraData(::grpc::ClientContext* context, const ::CameraDataRequest& request, ::CameraDataResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CameraDataResponse>> AsyncSendCameraData(::grpc::ClientContext* context, const ::CameraDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CameraDataResponse>>(AsyncSendCameraDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CameraDataResponse>> PrepareAsyncSendCameraData(::grpc::ClientContext* context, const ::CameraDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::CameraDataResponse>>(PrepareAsyncSendCameraDataRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // Define the RPC method for sending camera data
      //
      virtual void SendCameraData(::grpc::ClientContext* context, const ::CameraDataRequest* request, ::CameraDataResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SendCameraData(::grpc::ClientContext* context, const ::CameraDataRequest* request, ::CameraDataResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::CameraDataResponse>* AsyncSendCameraDataRaw(::grpc::ClientContext* context, const ::CameraDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::CameraDataResponse>* PrepareAsyncSendCameraDataRaw(::grpc::ClientContext* context, const ::CameraDataRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SendCameraData(::grpc::ClientContext* context, const ::CameraDataRequest& request, ::CameraDataResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CameraDataResponse>> AsyncSendCameraData(::grpc::ClientContext* context, const ::CameraDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CameraDataResponse>>(AsyncSendCameraDataRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CameraDataResponse>> PrepareAsyncSendCameraData(::grpc::ClientContext* context, const ::CameraDataRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::CameraDataResponse>>(PrepareAsyncSendCameraDataRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SendCameraData(::grpc::ClientContext* context, const ::CameraDataRequest* request, ::CameraDataResponse* response, std::function<void(::grpc::Status)>) override;
      void SendCameraData(::grpc::ClientContext* context, const ::CameraDataRequest* request, ::CameraDataResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::CameraDataResponse>* AsyncSendCameraDataRaw(::grpc::ClientContext* context, const ::CameraDataRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::CameraDataResponse>* PrepareAsyncSendCameraDataRaw(::grpc::ClientContext* context, const ::CameraDataRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SendCameraData_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Define the RPC method for sending camera data
    //
    virtual ::grpc::Status SendCameraData(::grpc::ServerContext* context, const ::CameraDataRequest* request, ::CameraDataResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SendCameraData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SendCameraData() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SendCameraData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCameraData(::grpc::ServerContext* /*context*/, const ::CameraDataRequest* /*request*/, ::CameraDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendCameraData(::grpc::ServerContext* context, ::CameraDataRequest* request, ::grpc::ServerAsyncResponseWriter< ::CameraDataResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SendCameraData<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SendCameraData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SendCameraData() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::CameraDataRequest, ::CameraDataResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::CameraDataRequest* request, ::CameraDataResponse* response) { return this->SendCameraData(context, request, response); }));}
    void SetMessageAllocatorFor_SendCameraData(
        ::grpc::MessageAllocator< ::CameraDataRequest, ::CameraDataResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::CameraDataRequest, ::CameraDataResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SendCameraData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCameraData(::grpc::ServerContext* /*context*/, const ::CameraDataRequest* /*request*/, ::CameraDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendCameraData(
      ::grpc::CallbackServerContext* /*context*/, const ::CameraDataRequest* /*request*/, ::CameraDataResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SendCameraData<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SendCameraData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SendCameraData() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SendCameraData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCameraData(::grpc::ServerContext* /*context*/, const ::CameraDataRequest* /*request*/, ::CameraDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SendCameraData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SendCameraData() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SendCameraData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCameraData(::grpc::ServerContext* /*context*/, const ::CameraDataRequest* /*request*/, ::CameraDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSendCameraData(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SendCameraData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SendCameraData() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SendCameraData(context, request, response); }));
    }
    ~WithRawCallbackMethod_SendCameraData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SendCameraData(::grpc::ServerContext* /*context*/, const ::CameraDataRequest* /*request*/, ::CameraDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SendCameraData(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SendCameraData : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SendCameraData() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::CameraDataRequest, ::CameraDataResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::CameraDataRequest, ::CameraDataResponse>* streamer) {
                       return this->StreamedSendCameraData(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SendCameraData() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SendCameraData(::grpc::ServerContext* /*context*/, const ::CameraDataRequest* /*request*/, ::CameraDataResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSendCameraData(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::CameraDataRequest,::CameraDataResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SendCameraData<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SendCameraData<Service > StreamedService;
};


#endif  // GRPC_camera_5fservice_2eproto__INCLUDED
