// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: camera_service.proto

#include "camera_service.pb.h"
#include "camera_service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* CameraService_method_names[] = {
  "/CameraService/SendCameraData",
};

std::unique_ptr< CameraService::Stub> CameraService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CameraService::Stub> stub(new CameraService::Stub(channel, options));
  return stub;
}

CameraService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SendCameraData_(CameraService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status CameraService::Stub::SendCameraData(::grpc::ClientContext* context, const ::CameraDataRequest& request, ::CameraDataResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::CameraDataRequest, ::CameraDataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendCameraData_, context, request, response);
}

void CameraService::Stub::async::SendCameraData(::grpc::ClientContext* context, const ::CameraDataRequest* request, ::CameraDataResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::CameraDataRequest, ::CameraDataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendCameraData_, context, request, response, std::move(f));
}

void CameraService::Stub::async::SendCameraData(::grpc::ClientContext* context, const ::CameraDataRequest* request, ::CameraDataResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendCameraData_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::CameraDataResponse>* CameraService::Stub::PrepareAsyncSendCameraDataRaw(::grpc::ClientContext* context, const ::CameraDataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::CameraDataResponse, ::CameraDataRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendCameraData_, context, request);
}

::grpc::ClientAsyncResponseReader< ::CameraDataResponse>* CameraService::Stub::AsyncSendCameraDataRaw(::grpc::ClientContext* context, const ::CameraDataRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSendCameraDataRaw(context, request, cq);
  result->StartCall();
  return result;
}

CameraService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CameraService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< CameraService::Service, ::CameraDataRequest, ::CameraDataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](CameraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::CameraDataRequest* req,
             ::CameraDataResponse* resp) {
               return service->SendCameraData(ctx, req, resp);
             }, this)));
}

CameraService::Service::~Service() {
}

::grpc::Status CameraService::Service::SendCameraData(::grpc::ServerContext* context, const ::CameraDataRequest* request, ::CameraDataResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


